apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-one
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app-one
    template:
        metadata:
            labels:
                app: app-one
        spec:
            containers:
              - name: app-one
                image: nginx:latest
                imagePullPolicy: Always
                ports:
                  - containerPort: 80
                    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-two
spec:
    replicas: 3
    selector:
        matchLabels:
            app: app-two
    template:
        metadata:
            labels:
                app: app-two
        spec:
            containers:
              - name: app-two
                image: wordpress:latest
                imagePullPolicy: Always
                ports:
                  - containerPort: 80
                    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-three
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app-three
    template:
        metadata:
            labels:
                app: app-three
        spec:
            containers:
              - name: app-three
                image: httpd:latest
                imagePullPolicy: Always
                ports:
                  - containerPort: 80
                    protocol: TCP            