Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.vm.define "liperezS" do |m1|
    m1.vm.hostname = "liperezS"
    m1.vm.network "private_network", ip: "192.168.56.110"

    m1.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    
    m1.vm.provision "shell", path: "./scripts/server.sh"
  end
end
