Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"

  config.vm.define "machine1" do |m1|
    m1.vm.hostname = "liperezS"
    m1.vm.network "private_network", ip: "192.168.56.110"

    m1.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end

  config.vm.define "machine2" do |m2|
    m2.vm.hostname = "liperezSW"
    m2.vm.network "private_network", ip: "192.168.56.111"

    m2.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end
end